id: docker_downloads
title: Docker 指定时间段下载量
description: KWDB Docker 在所选时间范围内的总下载量
queryModule: downloadsDocker
viz: stat
order: 3
colSpan: 1
options:
  decimals: 0
  suffix: ''
defaultTimeRange:
  from: now-30d
  to: now
refreshSec: 60
