id: github_downloads
title: GitHub 指定时间段下载量
description: KWDB GitHub 在所选时间范围内的总下载量
queryModule: downloadsGithub
viz: stat 
order: 6
colSpan: 1
options:
  decimals: 0
  suffix: ''
defaultTimeRange:
  from: now-30d
  to: now
refreshSec: 60
